config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :budgets do
    resources :projects do
      resources :votes, only: :create
    end
  end

  root 'budgets#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, Budget
    else
      can :read, Budget
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  has_many :projects, dependent: :destroy

  def voted_by?(user)
    Vote.exists?(budget_id: self.id, user_id: user.id)
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  belongs_to :budget

  def votes
    Vote.where(project_id: self.id).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_create :make_admin_if_first

  has_many :projects

  private

  def make_admin_if_first
    if User.count == 0
      self.admin = 1
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :budget
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  load_and_authorize_resource

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:name, :description, :amount, :amount_per_project)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_budget
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.budget = @budget
    @project.user = current_user
    respond_to do |format|
      if @project.save
        format.html { redirect_to @budget, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @budget, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_budget
      @budget = Budget.find(params[:budget_id])
    end

    def set_project
      @project = @budget.projects.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :amount, :budget_id, :user_id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_parents
  before_action :cheating_protection

  def create
    @vote = Vote.new
    @vote.user = current_user
    @vote.budget = @budget
    @vote.project = @project
    @vote.save
    redirect_to @budget, notice: "Dziękujemy za oddanie głosu na projekt #{@project.name}"
  end

  private

  def set_parents
    @budget = Budget.find(params[:budget_id])
    @project = @budget.projects.find(params[:project_id])
  end

  def cheating_protection
    if @budget.voted_by?(current_user)
      redirect_to @budget, error: 'Nie można głosować dwa razy w ramach tego samego budżetu' and return
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/address/_form.html.haml
= form_for @address, html: { class: "form form-horizontal address" } do |f|
  .form-group
    = f.label :first_name, class: 'control-label'
    .controls
      = f.text_field :first_name, class: 'form-control', required: true
    = error_span(@address[:first_name])
  .form-group
    = f.label :second_name, class: 'control-label'
    .controls
      = f.text_field :second_name, class: 'form-control', required: true
    = error_span(@address[:second_name])
  .form-group
    = f.label :last_name, class: 'control-label'
    .controls
      = f.text_field :last_name, class: 'form-control', required: true
    = error_span(@address[:last_name])
  .form-group
    = f.label :city, class: 'control-label'
    .controls
      = f.text_field :city, class: 'form-control', required: true
    = error_span(@address[:city])
  .form-group
    = f.label :address_line_1, class: 'control-label'
    .controls
      = f.text_field :address_line_1, class: 'form-control', required: true
    = error_span(@address[:address_line_1])
  .form-group
    = f.label :address_line_2, class: 'control-label'
    .controls
      = f.text_field :address_line_2, class: 'form-control', required: true
    = error_span(@address[:address_line_2])
  .form-group
    = f.label :zip_code, class: 'control-label'
    .controls
      = f.text_field :zip_code, class: 'form-control', required: true
    = error_span(@address[:zip_code])
  .form-group
    = f.label :id_number, class: 'control-label'
    .controls
      = f.text_field :id_number, class: 'form-control', required: true
    = error_span(@address[:id_number])
  .form-group
    = f.label :personal_number, class: 'control-label'
    .controls
      = f.text_field :personal_number, class: 'form-control', required: true
    = error_span(@address[:personal_number])
  .form-group
    = f.label :user_id, class: 'control-label'
    .controls
      = f.text_field :user_id, class: 'form-control', required: true
    = error_span(@address[:user_id])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), addresses_path, :class => 'btn btn-default'

app/views/address/edit.html.haml
- model_class = Address
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/address/index.html.haml
- model_class = Address
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:first_name)
      %th= model_class.human_attribute_name(:second_name)
      %th= model_class.human_attribute_name(:last_name)
      %th= model_class.human_attribute_name(:city)
      %th= model_class.human_attribute_name(:address_line_1)
      %th= model_class.human_attribute_name(:address_line_2)
      %th= model_class.human_attribute_name(:zip_code)
      %th= model_class.human_attribute_name(:id_number)
      %th= model_class.human_attribute_name(:personal_number)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @addresses.each do |address|
      %tr
        %td= link_to address.id, address_path(address)
        %td= address.first_name
        %td= address.second_name
        %td= address.last_name
        %td= address.city
        %td= address.address_line_1
        %td= address.address_line_2
        %td= address.zip_code
        %td= address.id_number
        %td= address.personal_number
        %td= address.user_id
        %td=l address.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_address_path(address), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), address_path(address), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_address_path, :class => 'btn btn-primary'

app/views/address/new.html.haml
- model_class = Address
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/address/show.html.haml
- model_class = Address
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:first_name) + ':'
  %br
  = @address.first_name
%p
  %strong= model_class.human_attribute_name(:second_name) + ':'
  %br
  = @address.second_name
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @address.last_name
%p
  %strong= model_class.human_attribute_name(:city) + ':'
  %br
  = @address.city
%p
  %strong= model_class.human_attribute_name(:address_line_1) + ':'
  %br
  = @address.address_line_1
%p
  %strong= model_class.human_attribute_name(:address_line_2) + ':'
  %br
  = @address.address_line_2
%p
  %strong= model_class.human_attribute_name(:zip_code) + ':'
  %br
  = @address.zip_code
%p
  %strong= model_class.human_attribute_name(:id_number) + ':'
  %br
  = @address.id_number
%p
  %strong= model_class.human_attribute_name(:personal_number) + ':'
  %br
  = @address.personal_number
%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @address.user_id


= link_to t('.back', :default => t("helpers.links.back")), addresses_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_address_path(@address), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), address_path(@address), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/budgets/_form.html.haml
= form_for @budget, html: { class: "form form-horizontal budget" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@budget[:name])
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_field :description, class: 'form-control', required: true
    = error_span(@budget[:description])
  .form-group
    = f.label :amount, class: 'control-label'
    .controls
      = f.text_field :amount, class: 'form-control', required: true
    = error_span(@budget[:amount])
  .form-group
    = f.label :amount_per_project, class: 'control-label'
    .controls
      = f.text_field :amount_per_project, class: 'form-control', required: true
    = error_span(@budget[:amount_per_project])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), budgets_path, :class => 'btn btn-default'

app/views/budgets/edit.html.haml
- model_class = Budget
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/budgets/index.html.haml
- model_class = Budget
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:amount)
      %th= model_class.human_attribute_name(:amount_per_project)
      - if can? :manage, Budget.new
        %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @budgets.each do |budget|
      %tr
        %td= link_to budget.id, budget_path(budget)
        %td= link_to budget.name, budget_path(budget)
        %td= link_to budget.description, budget_path(budget)
        %td= link_to number_to_currency(budget.amount), budget_path(budget)
        %td= link_to number_to_currency(budget.amount_per_project), budget_path(budget)
        - if can? :manage, budget
          %td
            = link_to t('.edit', :default => t("helpers.links.edit")), edit_budget_path(budget), :class => 'btn btn-default btn-xs'
            = link_to t('.destroy', :default => t("helpers.links.destroy")), budget_path(budget), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

- if can? :create, Budget.new
  = link_to t('.new', :default => t("helpers.links.new")), new_budget_path, :class => 'btn btn-primary'

app/views/budgets/new.html.haml
- model_class = Budget
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/budgets/show.html.haml
- model_class = Budget
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

- if @budget.voted_by?(current_user)
  .alert.alert-success
    Już oddałeś swój głos w ramach tego budżetu
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @budget.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @budget.description
%p
  %strong= model_class.human_attribute_name(:amount) + ':'
  %br
  = number_to_currency @budget.amount
%p
  %strong= model_class.human_attribute_name(:amount_per_project) + ':'
  %br
  = number_to_currency @budget.amount_per_project

%ul.list-inline
  %li
    %h2 Projekty
  %li= link_to 'Dodaj nowy', new_budget_project_path(budget_id: @budget), class: 'btn btn-primary'
%ul
  - @budget.projects.each do |project|
    %li
      %h4= link_to "#{project.name} (#{project.votes} głosów)", [@budget, project]


= link_to t('.back', :default => t("helpers.links.back")), budgets_path, :class => 'btn btn-default'
- if can? :manage, @budget
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_budget_path(@budget), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), budget_path(@budget), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BudzetObywatelski"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="#") BudzetObywatelski
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to "Budgets", budgets_path
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li= link_to 'Sign Out', destroy_user_session_path, method: :delete
            - else
              %li= link_to 'Sign Up', new_user_registration_path
              %li= link_to 'Sign In', new_user_session_path


    .container
      .row
        .col-lg-12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Company 2014

app/views/projects/_form.html.haml
= form_for [@budget, @project], html: { class: "form form-horizontal project" } do |f|
  .form-group
    = f.label :name, class: 'control-label'
    .controls
      = f.text_field :name, class: 'form-control', required: true
    = error_span(@project[:name])
  .form-group
    = f.label :description, class: 'control-label'
    .controls
      = f.text_area :description, class: 'form-control', required: true
    = error_span(@project[:description])
  .form-group
    = f.label :amount, class: 'control-label'
    .controls
      = f.text_field :amount, class: 'form-control', required: true
    = error_span(@project[:amount])
  = f.submit nil,class: 'btn btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), @budget, :class => 'btn btn-default'

app/views/projects/edit.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/index.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:amount)
      %th= model_class.human_attribute_name(:budget_id)
      %th= model_class.human_attribute_name(:user_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @projects.each do |project|
      %tr
        %td= link_to project.id, project_path(project)
        %td= project.name
        %td= project.description
        %td= project.amount
        %td= project.budget_id
        %td= project.user_id
        %td=l project.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_project_path(project), :class => 'btn btn-default btn-xs'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), project_path(project), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_project_path, :class => 'btn btn-primary'

app/views/projects/new.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/projects/show.html.haml
- model_class = Project
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @project.name
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @project.description
%p
  %strong= model_class.human_attribute_name(:amount) + ':'
  %br
  = number_to_currency @project.amount


= link_to t('.back', :default => t("helpers.links.back")), @budget, :class => 'btn btn-default'

- if @budget.voted_by?(current_user)
  .alert.alert-success
    Już oddałeś głos w ramach tego budżetu
- else
  = link_to 'Zagłosuj', budget_project_votes_path(budget_id: @budget, project_id: @project), method: :post, class: 'btn btn-danger'